# Change prefix key to Ctrl+a
set -g prefix C-a

# Enable mouse
set -g mouse on

# Clipboard options
set -g paste-detection on

# Scrollback history
set -g history-limit 5000

# Predictions
set -g allow-predictions on
set -g prediction-dimming off

# Pane selection 
bind-key \ split-window -h
bind-key - split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


